source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MZCoreDataBrowser_Example', :exclusive => true do
  pod "MZCoreDataBrowser", :path => "../"
end

target 'MZCoreDataBrowser_Tests', :exclusive => true do
  pod "MZCoreDataBrowser", :path => "../"

  
end
